services:
  - type: web
    name: whale-alert-bot
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: MIN_VOLUME
        value: "5000"
      - key: RENDER
        value: "true"
